added navabr
girlscript/Girscript-Community-Website pull request #79
Opened 2021-04-01 11:16 UTC by shreyanshi16

# Description

Added Navbar

Closes #53 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

https://user-images.githubusercontent.com/53462278/113285935-2b936200-9309-11eb-88d4-bac97ea0b8b7.mp4

2021-04-02 05:27 UTC, codewithvk requested changes
@shreyanshi16 Make these changes!

2021-04-02 05:27 UTC, codewithvk commented on frontend/src/Components/Navbar/Navbar.js
> +const Button = styled.button`
Please write CSS code in `navbar.css`

2021-04-02 13:45 UTC, shreyanshi16 commented on frontend/src/Components/Navbar/Navbar.js
> +const Button = styled.button`
Done!

2021-04-02 14:05 UTC, codewithvk commented
@shreyanshi16 Please resolve conflict.

2021-04-05 17:03 UTC, shreyanshi16 commented
@codewithvk conflict resolved

2021-04-06 03:46 UTC, merged

2021-04-06 03:46 UTC, codewithvk commented
Thanks for PR @shreyanshi16