Added our-community and our-impact section
girlscript/Girscript-Community-Website pull request #89
Opened 2021-04-15 13:16 UTC by SharmaTanish

# Description

I have added our-community and our-impact section under above issue using react .
@codewithvk please have a look !

Closes #78

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules
## Screenshots
![Screenshot (1602)](https://user-images.githubusercontent.com/75024552/114875058-8c975b80-9e1a-11eb-95cb-e4d9e081e466.png)

![Screenshot (1603)](https://user-images.githubusercontent.com/75024552/114875141-a0db5880-9e1a-11eb-9f50-af8e06ca292d.png)

2021-04-15 16:30 UTC, codewithvk requested changes
Hey @SharmaTanish , Please make the above changes!
If you have any query you can react me out by discord or here.

2021-04-15 16:30 UTC, codewithvk commented on frontend/src/App.js
> +  const data01 = [
For fake/Test_data , You can create new file on `frontend/src/Test_data/` and fetch from there!

2021-04-15 16:30 UTC, codewithvk commented on frontend/src/App.js
> +      <h1 className="our_impact" ><b>OUR IMPACT</b></h1>
Hey @SharmaTanish , Please make a separate component for that, for reference you can see `frontend/src/Components/Navbar/`.

App.js Use only for a component call with the router.

2021-04-16 11:42 UTC, SharmaTanish commented
Hi @codewithvk I have successfully made the changes you have requested ! Please have a look ?

2021-04-16 18:16 UTC, merged

2021-04-17 07:23 UTC, SharmaTanish commented
Thank you @codewithvk for your guidance and support 😀!