Upcoming events section added
girlscript/Girscript-Community-Website pull request #92
Opened 2021-04-18 18:44 UTC by rutuja2229

# Description

Created an  Upcoming event section

Closes #58 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

![image](https://user-images.githubusercontent.com/65710803/115156876-1efe6000-a0a4-11eb-8674-648f88ed5ffb.png)

2021-04-18 18:48 UTC, rutuja2229 commented
@codewithvk Please take a review at this, will the colour seems good to you?
I was unable to make it similar to that mentioned in the issue, any suggestions will be helpful for me. And apologies for the delay.

2021-04-18 19:13 UTC, codewithvk requested changes

2021-04-18 19:13 UTC, codewithvk commented on frontend/src/Components/Upcomingeve/Upcomingevents.js
> +                    <Card   id = 'upcomingeve' style={{ width: '18rem' }}  >
You should create one object for all dummy data, Fetch here and through map/ Create separate component for Cart item.

2021-04-18 19:13 UTC, codewithvk commented on frontend/src/Components/Upcomingeve/Upcomingevents.js
> +                    <Card   id = 'upcomingeve' style={{ width: '18rem' }}  >
@rutuja2229 make the above changes.

2021-04-20 15:18 UTC, rutuja2229 commented
Can u please check this again?

2021-05-07 13:55 UTC, rutuja2229 commented
@codewithvk can u plz reply?

2021-05-07 14:47 UTC, merged

2021-05-07 14:50 UTC, codewithvk commented
@rutuja2229 Sorry for the late reply, But unfortunately this project work was stoped according to the admin statement. So humble request don't work on this project until I will inform you. If you work with on my mentoring you can check my second project by [here](https://github.com/purnima143/Kurakoo)